name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: behe/heroku-build@v1
        with:
          app-name: "compsys-dropouts-personal-crm"
          api-key: "${{secrets.HEROKU_API_KEY}}"
          path: "optional-path-of-build-to-deploy"
